
---
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
extends:
  - "plugin:@typescript-eslint/recommended"
rules:
  no-unused-vars:
    - warn
  no-use-before-define:
    - warn
  "@typescript-eslint/no-use-before-define":
    - warn
  no-unused-expressions:
    - error